{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-lotzapp-database-data"
  labels:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.database.storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size | quote }}
{{- end }}
