apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-lotzapp-ftp"
  labels:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: ftp
spec:
  replicas: {{ .Values.ftp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: lotzapp
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: ftp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lotzapp
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: ftp
    spec:
      containers:
        - name: ftp
          image: "{{ .Values.images.ftp.repository }}:{{ .Values.images.ftp.tag }}"
          imagePullPolicy: {{ .Values.images.ftp.pullPolicy }}
          env:
            - name: AUTH_METHOD
              value: mysql
          ports:
            - name: ftp-control
              containerPort: 2100
              protocol: TCP
            {{- $start := int .Values.ftp.service.passivePortStart }}
            {{- $end := int .Values.ftp.service.passivePortEnd }}
            {{- range $i := until (int (add1 (sub $end $start))) }}
            {{- $port := add $start $i }}
            - containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: ftp-config
              mountPath: /data
            - name: documents
              mountPath: /ftpdata/documents
            - name: data
              mountPath: /ftpdata/data
      volumes:
        - name: ftp-config
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-lotzapp-ftp-config"
        - name: documents
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-lotzapp-documents"
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-lotzapp-data"
