{{- if .Values.ftp.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-lotzapp-ftp-config"
  labels:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: ftp
spec:
  accessModes:
    - {{ .Values.ftp.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.ftp.persistence.config.size | quote }}
{{- end }}
