apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-lotzapp-ftp"
  labels:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: ftp
spec:
  type: {{ .Values.ftp.service.type }}
  ports:
    - name: ftp-control
      port: {{ .Values.ftp.service.controlPort }}
      targetPort: 2100
      protocol: TCP
    {{- $start := int .Values.ftp.service.passivePortStart }}
    {{- $end := int .Values.ftp.service.passivePortEnd }}
    {{- range $i := until (int (add1 (sub $end $start))) }}
    {{- $port := add $start $i }}
    - name: ftp-p-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: ftp
