apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-lotzapp"
  labels:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: lotzapp
spec:
  {{- if .Values.lotzapp.ingress.className }}
  ingressClassName: {{ .Values.lotzapp.ingress.className }}
  {{- end }}
  rules:
    - host: {{ (index .Values.lotzapp.ingress.hosts 0).host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if .Values.lotzapp.nginx.enabled }}
                name: "{{ .Release.Name }}-lotzapp-nginx"
                port:
                  number: {{ .Values.lotzapp.nginx.service.port }}
                {{- else }}
                name: "{{ .Release.Name }}-lotzapp"
                port:
                  number: {{ .Values.lotzapp.service.port }}
                {{- end }}
