apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-lotzapp"
  labels:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: lotzapp
spec:
  replicas: {{.Values.lotzapp.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: lotzapp
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: lotzapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lotzapp
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: lotzapp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: migration
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{.Values.images.app.pullPolicy}}
          env:
            - name: MARIADB_HOST
              value: {{include "lotzapp.databaseHost" . | quote}}
            - name: MARIADB_PORT
              value: {{include "lotzapp.databasePort" . | quote}}
            - name: MARIADB_USER
              value: {{include "lotzapp.databaseUser" . | quote}}
            - name: MARIADB_PWD
              value: {{include "lotzapp.databasePassword" . | quote}}
          command:
            - bash
            - -c
            - 'cd /usr/src/migrations && ./wait-for-it.sh {{ include "lotzapp.databaseHost" . }}:{{ include "lotzapp.databasePort" . }} --strict --timeout=30 -- ./migrate.sh'
          volumeMounts:
            - name: migration-sql
              mountPath: /var/migration/initial_schema.sql
              subPath: initial_schema.sql
            - name: migration-sql
              mountPath: /var/migration/initial_inserts.sql
              subPath: initial_inserts.sql
      containers:
        - name: lotzapp
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{.Values.images.app.pullPolicy}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/www/html/data
            - name: documents
              mountPath: /var/www/html/documents
            - name: images
              mountPath: /var/www/html/images
            - name: home
              mountPath: /var/www/html/home
            - name: app-env
              mountPath: /var/www/html/.env
              subPath: .env
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-lotzapp-data"
        - name: documents
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-lotzapp-documents"
        - name: images
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-lotzapp-images"
        - name: home
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-lotzapp-home"
        - name: app-env
          secret:
            secretName: {{ .Values.lotzapp.envFile.secretName | default (printf "%s-lotzapp-env" .Release.Name) | quote }}
            items:
              - key: {{.Values.lotzapp.envFile.key | quote}}
                path: .env
        - name: migration-sql
          configMap:
            name: "{{ .Release.Name }}-lotzapp-migration"
