{{- if and .Values.webshop.enabled .Values.webshop.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-webshop"
  labels:
    app.kubernetes.io/name: lotzapp
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: webshop
  {{- with .Values.webshop.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webshop.ingress.className }}
  ingressClassName: {{ .Values.webshop.ingress.className }}
  {{- end }}
  {{- if .Values.webshop.ingress.tls }}
  tls:
    {{- toYaml .Values.webshop.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.webshop.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: "{{ $.Release.Name }}-webshop"
                port:
                  number: {{ $.Values.webshop.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
