apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vapid-generator.fullname" . }}
  namespace: {{ include "vapid-generator.secretNamespace" . }}
  labels:
    {{- include "vapid-generator.labels" . | nindent 4 }}
  annotations:
    {{- include "vapid-generator.annotations" . | nindent 4 }}
data:
  generate.js: |
    {{- include "vapid-generator.script" . | nindent 4 }}
