apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vapid-generator.serviceAccountName" . }}
  namespace: {{ include "vapid-generator.secretNamespace" . }}
  labels:
    {{- include "vapid-generator.labels" . | nindent 4 }}
  annotations:
    {{- include "vapid-generator.annotations" . | nindent 4 }}
