apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  instances: {{ .Values.instances }}

  imageName: {{ .Values.imageName | quote }}

  bootstrap:
    initdb:
      database: {{ .Values.bootstrap.initdb.database | quote }}
      owner: {{ .Values.bootstrap.initdb.owner | quote }}

  storage:
    size: {{ .Values.storage.size | quote }}

  postgresql:
    parameters:
      {{- range $key, $value := .Values.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}

  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
