apiVersion: v2
name: sharebubble
description: A Helm chart for Sharebubble - Community Network application
type: application
version: 0.2.0
appVersion: "0.2.0"

keywords:
  - bubble
  - sharebubble
  - community
  - django
  - celery
  - nginx

maintainers:
  - name: Treibhaus Donaufeld
    url: https://github.com/treibhausdonaufeld

home: https://github.com/treibhausdonaufeld/bubble
sources:
  - https://github.com/treibhausdonaufeld/bubble

dependencies: []
